#!/bin/bash
JRE_LOCAL_PATH=./jre/bin/java
PID=$(ps -ef | grep fanyi_project-1.0-SNAPSHOT.jar | grep -v "grep" | awk '{print $2}')

if test  ! -z "$PID"
  then
    kill -9 "$PID"
fi
if [ ! -d "$JRE_LOCAL_PATH" ]; then
    $JAVA_HOME/bin/java -jar ./fanyi_project-1.0-SNAPSHOT.jar
else
    $JRE_LOCAL_PATH -jar ./fanyi_project-1.0-SNAPSHOT.jar
fi
